# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NativeExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NativeExample
 pod 'AMRSDK', '~> 1.5'
  #mediation adapters
	pod 'AMRAdapterAdmob'
end
